import '../utils/constants.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';
import '../models/category.dart';

class AdminChildCategoriesView extends StatefulWidget { const AdminChildCategoriesView({super.key}); @override State<AdminChildCategoriesView> createState()=>_AdminChildCategoriesViewState(); }
class _AdminChildCategoriesViewState extends State<AdminChildCategoriesView>{
 final _name=TextEditingController(),_slug=TextEditingController(),_image=TextEditingController(),_sort=TextEditingController(text:'0');
 bool _active=true,_loading=true,_saving=false; int? _catId,_subId; ChildCategory? _editing; List<Category> _cats=[]; List<ChildCategory> _children=[];
 List<Subcategory> get _subs=>_catId==null?[]:_cats.firstWhere((c)=>int.tryParse(c.id)==_catId,orElse:()=>Category(id:'0',title:'',subtitle:'',imageUrl:'')).subcategories;
 @override void initState(){super.initState();_fetch();}
 Future<void> _fetch() async{setState(()=>_loading=true);final rs=await Future.wait([http.get(Uri.parse('${AppConstants.apiUrl}/categories')),http.get(Uri.parse('${AppConstants.apiUrl}/child-categories'))]);if(mounted)setState((){_cats=rs[0].statusCode==200?(json.decode(rs[0].body) as List).map((e)=>Category.fromJson(e)).toList():[];_children=rs[1].statusCode==200?(json.decode(rs[1].body) as List).map((e)=>ChildCategory.fromJson(e)).toList():[];_loading=false;});}
 void _edit(ChildCategory? c){setState((){_editing=c;_catId=c?.categoryId;_subId=c?.subcategoryId;_name.text=c?.name??'';_slug.text=c?.slug??'';_image.text=c?.imageUrl??'';_sort.text=(c?.sortOrder??0).toString();_active=c?.isActive??true;});}
 Future<void> _save() async{if(_catId==null||_subId==null||_name.text.trim().isEmpty)return;setState(()=>_saving=true);final token=context.read<AuthProvider>().token;final body=json.encode({'category_id':_catId,'subcategory_id':_subId,'name':_name.text.trim(),'slug':_slug.text.trim().isEmpty?null:_slug.text.trim(),'image_url':_image.text.trim(),'sort_order':int.tryParse(_sort.text)??0,'is_active':_active});final uri=Uri.parse('${AppConstants.apiUrl}/child-categories${_editing==null?'':'/${_editing!.id}'}');final r=_editing==null?await http.post(uri,headers:{'Content-Type':'application/json','Authorization':'Bearer $token'},body:body):await http.put(uri,headers:{'Content-Type':'application/json','Authorization':'Bearer $token'},body:body);if(mounted){setState(()=>_saving=false);if(r.statusCode==200||r.statusCode==201){_edit(null);_fetch();}else{ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Save failed: ${r.body}')));}}}
 Future<void> _delete(ChildCategory c) async{final token=context.read<AuthProvider>().token;await http.delete(Uri.parse('${AppConstants.apiUrl}/child-categories/${c.id}'),headers:{'Authorization':'Bearer $token'});_fetch();}
 @override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Manage Child Categories',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:12,runSpacing:12,crossAxisAlignment:WrapCrossAlignment.center,children:[SizedBox(width:220,child:DropdownButtonFormField<int>(value:_catId,decoration:const InputDecoration(labelText:'Category'),items:_cats.map((c)=>DropdownMenuItem(value:int.tryParse(c.id),child:Text(c.title))).toList(),onChanged:(v)=>setState((){_catId=v;_subId=null;}))),SizedBox(width:220,child:DropdownButtonFormField<int>(value:_subId,decoration:const InputDecoration(labelText:'Subcategory'),items:_subs.map((s)=>DropdownMenuItem(value:int.tryParse(s.id),child:Text(s.name))).toList(),onChanged:(v)=>setState(()=>_subId=v))),SizedBox(width:200,child:TextField(controller:_name,decoration:const InputDecoration(labelText:'Name'))),SizedBox(width:180,child:TextField(controller:_slug,decoration:const InputDecoration(labelText:'Slug'))),SizedBox(width:220,child:TextField(controller:_image,decoration:const InputDecoration(labelText:'Image URL'))),SizedBox(width:100,child:TextField(controller:_sort,decoration:const InputDecoration(labelText:'Sort'))),FilterChip(label:const Text('Active'),selected:_active,onSelected:(v)=>setState(()=>_active=v)),ElevatedButton(onPressed:_saving?null:_save,child:Text(_editing==null?'Add Child Category':'Update Child Category')),TextButton(onPressed:()=>_edit(null),child:const Text('Clear'))]))),const SizedBox(height:16),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):ListView.separated(itemCount:_children.length,separatorBuilder:(_,__)=>const Divider(),itemBuilder:(_,i){final c=_children[i];return ListTile(title:Text(c.name),subtitle:Text('Category ${c.categoryId} • Subcategory ${c.subcategoryId} • ${c.isActive?'Active':'Inactive'}'),trailing:Wrap(children:[IconButton(icon:const Icon(Icons.edit),onPressed:()=>_edit(c)),IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:()=>_delete(c))]));})),]);
}
